Library.create(name: 'Moravská zemská knihovna', code: 'mzk', url: 'http://kramerius.mzk.cz/')
Library.create(name: 'Národní digitální knihovna', code: 'ndk', url: 'http://krameriusndktest.mzk.cz/')
Library.create(name: 'Vědecká knihovna v Olomouci', code: 'vkol', url: 'http://kramerius.kr-olomoucky.cz/')
Library.create(name: 'Studijní a vědecká knihovna v Hradci Králové', code: 'svkhk', url: 'http://kramerius4.svkhk.cz/')
Library.create(name: 'Severočeská vědecká knihovna v Ústí nad Labem', code: 'svkul', url: 'http://kramerius4.svkul.cz/')
Library.create(name: 'Knihovna Akademie věd ČR', code: 'knav', url: 'http://kramerius.lib.cas.cz/')
Library.create(name: 'Městská knihovna Česká Třebová', code: 'mkct', url: 'http://k5.digiknihovna.cz/')
Library.create(name: 'Digitální studovna Ministerstva obrany ČR', code: 'dsmo', url: 'https://kramerius.army.cz/')
Library.create(name: 'Městská knihovna v Praze', code: 'mlp', url: 'http://kramerius4.mlp.cz/')
Library.create(name: 'Krajská knihovna Karlovy Vary', code: 'kkkv', url: 'http://k4.kr-karlovarsky.cz/')
Library.create(name: 'Krajská vědecká knihovna Liberec', code: 'kvkli', url: 'http://kramerius.kvkli.cz/')
Library.create(name: 'Studijní a vědecká knihovna Plzeňského kraje', code: 'svkpk', url: 'http://k4.svkpl.cz/')
Library.create(name: 'Národní filmový archiv', code: 'nfa', url: 'http://library.nfa.cz/')
Library.create(name: 'Židovské muzeum v Praze', code: 'zmp', url: 'http://kramerius4.jewishmuseum.cz/')
Library.create(name: 'Národní muzeum', code: 'nm', url: 'http://kramerius.nm.cz/')
Library.create(name: 'Knihovna Západočeského muzea v Plzni', code: 'zcm', url: 'http://kramerius.zcm.cz/')
Library.create(name: 'Jihočeská vědecká knihovna v Českých Budějovicích', code: 'cbvk', url: 'http://kramerius.cbvk.cz/')
Library.create(name: 'Krajská knihovna Františka Bartoše ve Zlíně', code: 'kfbz', url: 'http://dlib.kfbz.cz/')
Library.create(name: 'Národní knihovna', code: 'nkp', url: 'http://kramerius4.nkp.cz/')
Library.create(name: 'Univerzita Karlova v Praze - Fakulta sociálních věd', code: 'cuni_fsv', url: 'http://kramerius.fsv.cuni.cz/')
Library.create(name: 'Národní technická knihovna', code: 'ntk', url: 'http://kramerius.techlib.cz/')
Library.create(name: 'Středočeská vědecká knihovna v Kladně', code: 'svkkl', url: 'http://kramerius.svkkl.cz/')
Library.create(name: 'Lesnický a myslivecký digitální archiv', code: 'lmda', url: 'http://lmda.silvarium.cz/')
Library.create(name: 'Zemědělské poradensko-vzdělávací centrum a Knihovna Antonína Švehly', code: 'uzei', url: 'http://kramerius.uzei.cz/')
Library.create(name: 'Univerzitná knižnica v Bratislave', code: 'ukb', url: 'http://pc139.ulib.sk/')
Library.create(name: 'Slezská univerzita v Opavě', code: 'slu', url: 'http://kramerius.slu.cz/')
Library.create(name: 'Moravskoslezská vědecká knihovna v Ostravě', code: 'svkos', url: 'http://camea.svkos.cz/')
Library.create(name: 'Výzkumný ústav geodetický, topografický a kartografický', code: 'vugtk', url: 'http://knihovna-test.vugtk.cz/')
Library.create(name: 'Vysoká škola ekonomická v Praze', code: 'vse', url: 'http://kramerius.vse.cz/')
Library.create(name: 'Národní lékařská knihovna v Praze', code: 'nlk', url: 'http://kramerius.medvik.cz/')
Library.create(name: 'Mendelova univerzita v Brně', code: 'mendelu', url: 'http://kramerius4.mendelu.cz/')
Library.create(name: 'Krajská knihovna Vysočiny v Havlíčkově Brodě', code: 'kkvhb', url: 'http://kramerius.kkvysociny.cz/')